DevSf/force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <inlineHelpText>Enter Country Code only</inlineHelpText>
    <label>Languages</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

DevSf/force-app/main/default/objects/Contact/fields/survey_date__c.field-meta.xml
<CustomField>
    <fullName>survey_date__c</fullName>
    <label>survey date</label>
    <type>Date</type>
</CustomField>

DevSf/force-app/main/default/classes/SurveyBatch_Test.cls
@isTest
public class SurveyBatch_Test {
	/**
    * Parameters: None
    * Description: Create Contact Data
    * Return Type: Contact
    */
    // NOTE: Here we can create a Seprate class to expose all the test method and can all in respective test class as here we have only one method 
    // so created here only. 
    static testMethod void testMethod1() 
    {        
        	contact con = new contact();
            con.FirstName = 'Test FirstName';
            con.LastName = 'Last Name';
            con.Email = 'test@test.com';
            con.Languages__c = 'en';
            con.survey_date__c = Date.today();
    		insert con;
         
        Test.startTest();
 		
            SurveyBatch obj = new SurveyBatch();
            DataBase.executeBatch(obj); 
             
        Test.stopTest();
    }
}